version: '3.4'

services:
  skynet:
    platform: linux/amd64
    image: skynet
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
        - "nekofluff/skynet"
    environment:
      ENV_FILE: /run/secrets/env_file
    secrets:
       - env_file
secrets:
  env_file:
    file: .env