version: '3.4'

services:
  skynet:
    image: nekofluff/skynet:latest
    restart: always
    environment:
      ENV_FILE: /run/secrets/env_file
    secrets:
       - env_file
secrets:
  env_file:
    file: .env