name: Build Release

on:
  push:
    branches: ['main']

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Semantic Release
        uses: go-semantic-release/action@v1.17.0
        with:
          github-token: ${{ secrets.TOKEN }}
